# Generated by Django 3.1.3 on 2020-11-29 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ObservatorioTTApp', '0001_initial'),
        ('recursos', '0004_auto_20201125_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurso',
            old_name='origen',
            new_name='municipio',
        ),
        migrations.AddField(
            model_name='recurso',
            name='estado',
            field=models.ForeignKey(default='CMX', on_delete=django.db.models.deletion.CASCADE, to='ObservatorioTTApp.mexicostate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
