# Generated by Django 3.1.3 on 2021-01-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_auto_20201129_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursosarchivo',
            name='tipo',
            field=models.CharField(choices=[('IMG', 'IMG'), ('VID', 'VID')], default='IMG', max_length=3),
        ),
    ]
