# Generated by Django 3.1.3 on 2021-01-05 06:12

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0009_auto_20210105_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='recursos.TaggedWhatever', to='recursos.MyCustomTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='recursosarchivo',
            name='tipo',
            field=models.CharField(choices=[('IMG', 'IMG'), ('VID', 'VID')], default='IMG', max_length=3),
        ),
    ]
