# Generated by Django 3.1.5 on 2021-01-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0013_auto_20210110_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='html',
            field=models.TextField(null=True),
        ),
    ]
