# Generated by Django 3.1.5 on 2021-01-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0015_auto_20210112_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursosarchivo',
            name='tipo',
            field=models.CharField(choices=[('VID', 'VID'), ('IMG', 'IMG')], default='IMG', max_length=3),
        ),
    ]
