# Generated by Django 3.1.5 on 2021-01-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0019_auto_20210120_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursosarchivo',
            name='tipo',
            field=models.CharField(choices=[('IMG', 'IMG'), ('VID', 'VID')], default='IMG', max_length=3),
        ),
    ]
