# Generated by Django 3.1.5 on 2021-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0020_auto_20210120_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='autores',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='nombreRecurso',
            field=models.CharField(max_length=1000),
        ),
    ]
