# Generated by Django 3.1.5 on 2021-01-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0021_auto_20210120_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='Archivo',
            field=models.FileField(null=True, upload_to='Archivo'),
        ),
        migrations.AlterField(
            model_name='recursosarchivo',
            name='tipo',
            field=models.CharField(choices=[('VID', 'VID'), ('IMG', 'IMG')], default='IMG', max_length=3),
        ),
    ]
