# Generated by Django 3.1.3 on 2021-01-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='intereses',
        ),
    ]
