# Generated by Django 3.1.3 on 2021-01-05 06:07

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('usuarios', '0002_remove_profile_intereses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intereses',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
