# Generated by Django 3.1.3 on 2021-01-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_profile_intereses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='intereses',
        ),
    ]
