# Generated by Django 3.1.3 on 2021-01-05 06:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0011_auto_20210105_0613'),
        ('usuarios', '0004_remove_profile_intereses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intereses',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='recursos.TaggedWhatever', to='recursos.MyCustomTag', verbose_name='Tags'),
        ),
    ]
