# Generated by Django 3.1.3 on 2021-01-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObservatorioTTApp', '0001_initial'),
        ('usuarios', '0005_profile_intereses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(null=True, upload_to='Perfil_Fotos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ObservatorioTTApp.mexicomunicipio'),
        ),
    ]
