# Generated by Django 3.1.5 on 2021-01-10 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObservatorioTTApp', '0001_initial'),
        ('usuarios', '0006_auto_20210105_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ObservatorioTTApp.mexicostate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='semblanza',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
