# Generated by Django 3.1.5 on 2021-01-20 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObservatorioTTApp', '0002_intitucionempresa'),
        ('usuarios', '0007_auto_20210110_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ObservatorioTTApp.intitucionempresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='permiso',
            field=models.CharField(choices=[('ED', 'Editor'), ('LE', 'Lector')], default='LE', max_length=20),
        ),
    ]
