# Generated by Django 3.1 on 2020-10-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRecurso', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('entidadFederativa', models.CharField(choices=[('AGS', 'AGUASCALIENTES'), ('BC', 'BAJA CALIFORNIA'), ('BCS', 'BAJA CALIFORNIA SUR'), ('CHI', 'CHIHUAHUA'), ('CHS', 'CHIAPAS'), ('CMP', 'CAMPECHE'), ('CMX', 'CIUDAD DE MEXICO'), ('COA', 'COAHUILA'), ('COL', 'COLIMA'), ('DGO', 'DURANGO'), ('GRO', 'GUERRERO'), ('GTO', 'GUANAJUATO'), ('HGO', 'HIDALGO'), ('JAL', 'JALISCO'), ('MCH', 'MICHOACAN'), ('MEX', 'ESTADO DE MEXICO'), ('MOR', 'MORELOS'), ('NAY', 'NAYARIT'), ('NL', 'NUEVO LEON'), ('OAX', 'OAXACA'), ('PUE', 'PUEBLA'), ('QR', 'QUINTANA ROO'), ('QRO', 'QUERETARO'), ('SIN', 'SINALOA'), ('SLP', 'SAN LUIS POTOSI'), ('SON', 'SONORA'), ('TAB', 'TABASCO'), ('TLX', 'TLAXCALA'), ('TMS', 'TAMAULIPAS'), ('VER', 'VERACRUZ'), ('YUC', 'YUCATAN'), ('ZAC', 'ZACATECAS')], default='AGS', max_length=20)),
                ('autor', models.CharField(max_length=100)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('archivo', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
            },
        ),
    ]
