# Generated by Django 3.1 on 2020-10-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidoPaterno', models.CharField(max_length=20)),
                ('apellidoMaterno', models.CharField(max_length=20)),
                ('edad', models.IntegerField(max_length=3)),
                ('correoElectronico', models.EmailField(max_length=30)),
                ('contraseña', models.CharField(max_length=20)),
                ('preferencias', models.CharField(max_length=100)),
                ('permiso', models.CharField(choices=[('AD', 'Administrador'), ('GE', 'General'), ('IN', 'Investigador')], default='GE', max_length=20)),
                ('entidadFederativa', models.CharField(choices=[('AGS', 'AGUASCALIENTES'), ('BC', 'BAJA CALIFORNIA'), ('BCS', 'BAJA CALIFORNIA SUR'), ('CHI', 'CHIHUAHUA'), ('CHS', 'CHIAPAS'), ('CMP', 'CAMPECHE'), ('CMX', 'CIUDAD DE MEXICO'), ('COA', 'COAHUILA'), ('COL', 'COLIMA'), ('DGO', 'DURANGO'), ('GRO', 'GUERRERO'), ('GTO', 'GUANAJUATO'), ('HGO', 'HIDALGO'), ('JAL', 'JALISCO'), ('MCH', 'MICHOACAN'), ('MEX', 'ESTADO DE MEXICO'), ('MOR', 'MORELOS'), ('NAY', 'NAYARIT'), ('NL', 'NUEVO LEON'), ('OAX', 'OAXACA'), ('PUE', 'PUEBLA'), ('QR', 'QUINTANA ROO'), ('QRO', 'QUERETARO'), ('SIN', 'SINALOA'), ('SLP', 'SAN LUIS POTOSI'), ('SON', 'SONORA'), ('TAB', 'TABASCO'), ('TLX', 'TLAXCALA'), ('TMS', 'TAMAULIPAS'), ('VER', 'VERACRUZ'), ('YUC', 'YUCATAN'), ('ZAC', 'ZACATECAS')], default='AGS', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
