# Generated by Django 3.1.5 on 2021-01-10 03:54

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0013_auto_20210110_0246'),
        ('foroDiscusion', '0002_auto_20201229_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='forodiscusion',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='recursos.TaggedWhatever', to='recursos.MyCustomTag', verbose_name='Tags'),
        ),
    ]
