# Generated by Django 3.1.5 on 2021-01-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foroDiscusion', '0004_comentarioblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioblog',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
