# Generated by Django 3.1.5 on 2021-01-20 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObservatorioTTApp', '0002_intitucionempresa'),
        ('foroDiscusion', '0005_comentarioblog_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='forodiscusion',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ObservatorioTTApp.intitucionempresa'),
        ),
    ]
