# Generated by Django 3.1.5 on 2021-01-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foroDiscusion', '0006_forodiscusion_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='forodiscusion',
            name='Archivo',
            field=models.FileField(null=True, upload_to='Archivo'),
        ),
    ]
