# Generated by Django 3.1.5 on 2021-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObservatorioTTApp', '0002_intitucionempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mexicomunicipio',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
